name: molgrid
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - gxx<10
  - cmake>=3.18
  - cudatoolkit-dev=11.3
  - python<3.10
  - boost>=1.77
  - numpy
  - scipy
  - openbabel=3
  - pytorch
  - pytest

