name: molgrid
channels:
  - pytorch
  - conda-forge
dependencies:
  - gxx=10
  - zlib
  - cmake>=3.18
  - cudatoolkit-dev=11.3
  - python
  - boost
  - numpy
  - scipy
  - openbabel=3
  - pytorch::pytorch
  - pytest
  - psutil

