{% set version = "0.5.1" %}

package:
  name: molgrid
  version: {{ version }}

source:
  git_url: https://github.com/gnina/libmolgrid.git
  git_rev: tags/v{{ version }}
  git_depth: 1

build:
  number: 1

requirements:
  build:
    - gxx<10
    - cmake>=3.18
    - cudatoolkit-dev=11.3
  host:
    - python<3.10
    - boost>=1.77
    - numpy
    - scipy
    - openbabel=3
    - pytorch
    - pytest
  run:
    - cudatoolkit=11.3
    - python<3.10
    - boost>=1.77
    - numpy
    - scipy
    - openbabel=3
    - pytorch
    - pytest

test:
  imports:
    - molgrid
  requires:
    - pytest
  run:
    - pytest

about:
  home: https://gnina.github.io/libmolgrid/
  license: Apache 2.0, GNU 2
  summary: Comprehensive library for fast, GPU accelerated molecular gridding for deep learning workflows

extra:
  recipe-maintainers:
    - mattragoza


